version: "3.1"

networks:
  network:

services:
  web:
    image: nginx:1.19.2-alpine
    ports:
      - 433:433
      - 80:80
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - network

  usersvc:
    image: alpine:3.12.0
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    volumes:
      - ./backend/bin/usersvc:/bin/usersvc:ro
    networks: 
      - network
    command: usersvc
  
  # db:
  #   container_name: snam_db
  #   image: postgres:11.5
  #   environment: 
  #     POSTGRES_PASSWORD: password
  #     PGDATA: /var/lib/postgresql/data/snam
  #   volumes: 
  #     - snam_database:/var/lib/postgresql/data/snam
  #   networks: 
  #     - network